$('#num1').owlCarousel({
    margin:0,
    loop:true,
    autoplay:true,
    autoplayTimeout:5000,
    autoplayHoverPause:true,
    smartSpeed:5000,
    dots:true,
    nav:true,
    responsive:{
        0:{
            items:1
        },
        600:{
            items:1
        },
        1000:{
            items:1
        }
    }
})
$('#num2').owlCarousel({
    margin:30,
    loop:true,
    autoWidth:true,
    autoplay:true,
    autoplayHoverPause:true,
    smartSpeed:2000,
    fluidSpeed:2000,
    autoplayTimeout:2000,
    dots:false,
})